const dataJSON = [
  {
    "id":"100000",
    "name": "Ruben Maldonado",
    "type": "Bugs Detection",
    "message": "I can't see my profile.",
    "status" : "Assigned",
    "date": "05/08/2019 09:00:51",
  },
  {
    "id":"100001",
    "name": "Jan Oblak",
    "type": "Visual Appearance",
    "message": "The Feedback List it's very complicated to see.",
    "status" : "Created",
    "date": "05/04/2019 10:10:48",
  },
  {
    "id":"100002",
    "name": "Martin Delgadillo",
    "type": "Visual Appearance",
    "message": "I don't know what to write here.",
    "status" : "Finished",
    "date": "05/14/2019 10:55:39",
  },
  {
    "id":"100003",
    "name": "Charly Shean",
    "type": "New Service",
    "message": "I think that we need access to Facebook.",
    "status" : "Cancelled",
    "date": "01/28/2019 12:00:00",
  },
  {
    "id":"100004",
    "name": "Aldo Suarez",
    "type": "Bugs Detection",
    "message": "I can't create a new GitHub repository.",
    "status" : "In Progress",
    "date": "02/02/2019 22:15:38",
  },
  {
    "id":"100005",
    "name": "Victoria Torrez",
    "type": "General Praise",
    "message": "I Like this App.",
    "status" : "Archived",
    "date": "02/22/2019 15:05:09",
  },
  {
    "id":"100006",
    "name": "Javier Guizada",
    "type": "General Praise",
    "message": "Create my GitHub Account it was easy.",
    "status" : "Created",
    "date": "04/30/2019 15:35:59",
  },
  {
    "id":"100007",
    "name": "Jorge Galindo",
    "type": "General Praise",
    "message": "I think that this app is very quickly.",
    "status" : "Archived",
    "date": "04/10/2019 18:35:39",
  },
  {
    "id":"100008",
    "name": "Roberth Baratheon",
    "type": "Visual Appearance",
    "message": "I think that the profile can be seen better.",
    "status" : "In Progress",
    "date": "04/03/2019 17:02:02",
  },
  {
    "id":"100009",
    "name": "Owen Wilson",
    "type": "New Service",
    "message": "I think that we need access to Google Maps.",
    "status" : "Assigned",
    "date": "04/10/2019 20:15:15",
  },
  {
    "id":"100010",
    "name": "Victoria Torrez",
    "type": "General Praise",
    "message": "I Like this App.",
    "status" : "Created",
    "date": "03/25/2019 15:15:15",
  },
  {
    "id":"100011",
    "name": "Javier Guizada",
    "type": "General Praise",
    "message": "Create my GitHub Account it was easy.",
    "status" : "Archived",
    "date": "02/11/2019 10:10:10",
  },
  {
    "id":"100012",
    "name": "Jorge Galindo",
    "type": "Bugs Detection",
    "message": "Reset MFA does not working.",
    "status" : "Finished",
    "date": "05/08/2019 13:15:13",
  },
  {
    "id":"100013",
    "name": "Margaret Tyrel",
    "type": "New Service",
    "message": "I think that we need access to Twiter.",
    "status" : "Cancelled",
    "date": "05/07/2019 23:59:59",
  },
  {
    "id":"100014",
    "name": "Aldo Suarez",
    "type": "Bugs Detection",
    "message": "I can't create a new GitHub repository.",
    "status" : "Assigned",
    "date": "04/30/2019 20:20:20",
  },
  {
    "id":"100015",
    "name": "Roberth Baratheon",
    "type": "Suggestions",
    "message": "I think that the profile can be seen better.",
    "status" : "Created",
    "date": "02/05/2019 09:09:09",
  },
  {
    "id":"100016",
    "name": "Jan Oblak",
    "type": "Visual Appearance",
    "message": "The Feedback List it's very complicated to see.",
    "status" : "Assigned",
    "date": "05/05/2019 16:16:16",
  },
  
];

export default dataJSON;